# Generated by Django 5.1.1 on 2024-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_identity', models.CharField(max_length=100)),
                ('universe', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=500)),
                ('powers', models.TextField(max_length=500)),
            ],
        ),
    ]
