# Generated by Django 5.1.1 on 2024-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='powers',
            field=models.ManyToManyField(to='main_app.power'),
        ),
    ]
